services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:8084"
    env_file:
      - ../.env
    environment:
      SPRING_RABBITMQ_HOST: notification-service-db
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
    depends_on:
      - notification-service-db
      - service-discovery
    networks:
      - internal
    restart: unless-stopped

  notification-service-db:
    image: rabbitmq:3-management
    container_name: notification-service-db
    env_file:
      - ../.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${NOTIFICATION_SERVICE_DB_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - notification-service-db-data:/var/lib/rabbitmq
    networks:
      - internal
    restart: unless-stopped

volumes:
  notification-service-db-data: