services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    env_file:
      - ../.env
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
    networks:
      - internal
    restart: unless-stopped