services:
  rabbitmq:
    image: rabbitmq:4.3.1-management-alpine
    container_name: rabbitmq
    env_file:
      - ../../.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672" # Consider renaming this env var later to RABBITMQ_AMQP_PORT
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  rabbitmq-data:

networks:
  internal:
    external: true
    name: ${DOCKER_NETWORK}