spring.application.name=auth-service

server.port=8081
# spring.datasource.url=jdbc:postgresql://localhost:5432/usuario
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.sql.init.mode=always
# spring.jpa.hibernate.ddl-auto=update

# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# spring.config.import=optional:file:.env[.properties
logging.level.root=info