include:
  - path: ./auth-service/docker-compose.yml
  - path: ./paciente-service/docker-compose.yml
  - path: ./triagem-service/docker-compose.yml
  - path: ./notification-service/docker-compose.yml
  - path: ./service-discovery/docker-compose.yml
  - path: ./api-gateway/docker-compose.yml
  - path: ./bed-service/docker-compose.yml
  - path: ./medical-records-service/docker-compose.yml
  - path: ./observability/docker-compose.yml

networks:
  internal:
    external: true
    name: ${DOCKER_NETWORK}