version: '3.8'

services:
  # O Banco de dados exclusivo do Bed Service
  bed-db:
    image: postgres:15-alpine
    container_name: bed-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bed_db
    ports:
      - "5434:5432" # Porta externa 5434 para não chocar com o Postgres do Auth (5432)
    networks:
      - healthsys-internal
    volumes:
      - bed_db_data:/var/lib/postgresql/data

  # O Microserviço de Leitos
  bed-service:
    build: ./bed-service
    container_name: bed-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bed-db:5432/bed_db
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - bed-db
      - rabbitmq
    networks:
      - healthsys-internal

networks:
  healthsys-internal:
    external: true

volumes:
  bed_db_data: