server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - Authorization
                allowCredentials: true

          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: paciente-service
              uri: lb://paciente-service
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: triagem-service
              uri: lb://triagem-service
              predicates:
                - Path=/tri/**
              filters:
                - StripPrefix=1
                - JwtValidation

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

