server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Servicos de Usuario
            - id: auth-service-route
              uri: http://auth-service:8081
              predicates:
                - Path=/api/usuarios,/api/usuarios/**,/api/perfis/**
            # Servicos de Paciente
            - id: paciente-service-route
              uri: http://paciente-service:8082
              predicates:
                - Path=/api/pacientes/**,/api/generos/**,/api/telefones/**,/api/enderecos/**,/api/sexos/**,/api/alergias/**,/api/vacinas/**