server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: paciente-service-route
              uri: http://paciente-service:8082
              predicates:
                - Path=/api/pacientes,/api/pacientes/**,/api/generos/**,/api/telefones/**,/api/enderecos/**,/api/sexos/**,/api/alergias/**,/api/vacinas/**
            - id: usuario-service-route
              uri: http://usuario-service:8081
              predicates:
                - Path=/api/usuarios,/api/usuarios/**,/api/perfis/**
