spring.application.name=bed-service
server.port=8086

# Configuracao do Banco dentro da Rede do Docker (usa o nome do container do db)
spring.datasource.url=jdbc:postgresql://bed-db:5432/bed_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ apontando para o container correto
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password
spring.rabbitmq.template.retry.enabled=true

# Eureka Service Discovery
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Actuator - Health Checks e Metricas
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
