spring.application.name=bed-service
server.port=8086

# Configuração do Banco dentro da Rede do Docker (usa o nome do container do db)
spring.datasource.url=jdbc:postgresql://bed-db:5432/bed_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ apontando para o container correto
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password
spring.rabbitmq.template.retry.enabled=true