spring.application.name=medical-records-service
server.port=8085

# MongoDB - Prioriza a URI do Docker Compose
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:password@localhost:27017/medical_db?authSource=admin}

# RabbitMQ - Para enviar alertas ao Notification Service
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:password}


# Eureka Service Discovery
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Actuator - Health Checks e metricas
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

