spring.application.name=medical-records-service
server.port=8085

# MongoDB
spring.mongodb.host=${SPRING_MONGODB_HOST:localhost}
spring.mongodb.port=${SPRING_MONGODB_PORT:27017}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:medical_db}
spring.mongodb.username=${SPRING_MONGODB_USERNAME:admin}
spring.mongodb.password=${SPRING_MONGODB_PASSWORD:admin123}
spring.mongodb.authentication-database=${SPRING_MONGODB_AUTHENTICATION_DATABASE:admin}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:password}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}