spring.application.name=medical-records-service
server.port=8085

# MongoDB - Ajustado para usar as credenciais padronizadas do seu .env
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/medical_db?authSource=admin}

# RabbitMQ - Ajustado o fallback do Host para refletir o seu container real de mensageria
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:notification-service-db}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin123}

# Configuração de JSON para o Jackson (Importante para evitar quebra de datas no React/SSE)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.datatype.jsr310.key-deserializer=org.springframework.jackson.datatype.jsr310.deser.key.LocalDateKeyDeserializer