spring.application.name=pacientes

server.port=8082
logging.level.root = info


# spring.datasource.url=jdbc:postgresql://localhost:5432/paciente
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.sql.init.mode=always
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=true
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.config.import=optional:file:.env[.properties]