global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'healthsys'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'service-discovery:8761', 'auth-service:8081', 'paciente-service:8082', 'triagem-service:8083', 'notification-service:8084', 'medical-records-service:8085', 'bed-service:8086']
        labels:
          application: "HealthSys"

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: "API Gateway"

  - job_name: 'service-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['service-discovery:8761']
          labels:
            application: "Service Discovery"

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['auth-service:8081']
          labels:
            application: "Auth Service"

  - job_name: 'paciente-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['paciente-service:8082']
          labels:
            application: "Paciente Service"

  - job_name: 'triagem-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['triagem-service:8083']
          labels:
              application: "Triagem Service"

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['notification-service:8084']
          labels:
              application: "Notification Service"

  - job_name: 'medical-records-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['medical-records-service:8085']
          labels:
              application: "Medical Records Service"

  - job_name: 'bed-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['bed-service:8086']
          labels:
              application: "Bed Service"

