services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    env_file:
      - ../.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
    depends_on:
      auth-service-db:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${AUTH_SERVICE_DB_PORT}:5432"
    volumes:
      - auth-service-db-data:/var/lib/postgresql
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=\"${DB_PASSWORD}\" pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth-service-db-data: