services:
  medical-records-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-records-service
    ports:
      - "${MEDICAL_RECORDS_SERVICE_PORT}:8085"
    environment:
      # Injects the fully constructed URI using the fixed encoded password
      SPRING_MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@medical-records-service-db:27017/${MEDICAL_RECORDS_DB_NAME}?authSource=admin"
      SPRING_RABBITMQ_HOST: notification-service-db
      SPRING_RABBITMQ_PORT: ${RABBITMQ_AMQP_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    depends_on:
      medical-records-service-db:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped
    env_file:
      - ../.env

  medical-records-service-db:
    image: mongo:7.0.34
    container_name: medical-records-service-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MEDICAL_RECORDS_DB_NAME}
    ports:
      - "${MEDICAL_RECORDS_SERVICE_DB_PORT}:27017"
    volumes:
      - medical-records-service-db-data:/data/db
    networks:
      - internal
    restart: unless-stopped
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  internal:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  medical-records-service-db-data: