services:
  paciente-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paciente-service
    ports:
      - "${PACIENTE_SERVICE_PORT}:8082"
    env_file:
      - ../.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://paciente-service-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_REDIS_USERNAME: ${REDIS_USER}
    depends_on:
      paciente-service-db:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped

  paciente-service-db:
    image: postgres:18.4-alpine
    container_name: paciente-service-db
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PACIENTE_SERVICE_DB_PORT}:5432"
    volumes:
      - paciente-service-db-data:/var/lib/postgresql
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=\"${DB_PASSWORD}\" pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  paciente-service-db-data: